---
- hosts: localhost
  gather_facts: false

  vars:
    shell: 'bash'
    user: 'james'

  pre_tasks:
    - name: Update Apt cache if it hasn't been done in the past hour
      apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  tasks:
    - name: Configure Ubuntu settings
      include_role:
        name: ubuntu_settings

    - name: Setup Stow
      include_role:
        name: stow

    - name: Ensure XDG base directory variables are stowed
      command:
        chdir: '/home/{{ user }}/.dotfiles/'
        cmd: stow xdg-base-directories
        creates: '/home/{{ user }}/.config/environment.d/010-xdg.conf'

    - name: Setup profle
      include_role:
        name: profile

    - name: Ensure custom commands are in ~/.local/bin
      include_role:
        name: custom_commands

    - name: Setup shell
      include_role:
        name: '{{ shell }}'

    - name: Setup Vim
      include_role:
        name: vim
...
