---
- hosts: localhost
  become: true

  tasks:
    - name: update apt cache if it hasn't been done in the past hour
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
...
