---
- name: Ensure Vim is installed
  apt:
    name: vim
    state: present
  become: true

- name: Ensure Vim configs have been stowed
  command:
    chdir: '/home/{{ user }}/.dotfiles/'
    cmd: stow vim
    creates: '/home/{{ user }}/.vim/vimrc'
...
